version: "3.9"

services:
  server:
    container_name: server
    build:
      dockerfile: server/Dockerfile
    ports:
      - 50051:50051
    environment:
    - PYTHONUNBUFFERED=1

  client:
    container_name: client
    build:
      dockerfile: client/Dockerfile

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - 15672:15672
      - 5672:5672
