version: "3.9"

services:
  grpc_server:
    container_name: grpc_server
    build:
      dockerfile: grpc_server/Dockerfile
    ports:
      - 50051:50051

  rest_server:
    container_name: rest_server
    build:
      dockerfile: rest_server/Dockerfile
    ports:
      - 13372:13372

  graphql_server:
    container_name: graphql_server
    build:
      dockerfile: graphql_server/Dockerfile
    ports:
      - 13371:13371

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - 5672:5672

  client:
    container_name: client
    build:
      dockerfile: client/Dockerfile
