# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mafia.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bmafia.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x18\n\x08Username\x12\x0c\n\x04name\x18\x01 \x01(\t\"$\n\x05Users\x12\x1b\n\x08username\x18\x01 \x03(\x0b\x32\t.Username\"F\n\x10StartGameRequest\x12\x19\n\x06player\x18\x01 \x01(\x0b\x32\t.Username\x12\x17\n\x07players\x18\x02 \x01(\x0b\x32\x06.Users\"E\n\x11StartGameResponse\x12\x0f\n\x07game_id\x18\x01 \x01(\r\x12\x11\n\tplayer_id\x18\x02 \x01(\r\x12\x0c\n\x04role\x18\x03 \x01(\t2\x92\x01\n\x05Mafia\x12 \n\x07\x43onnect\x12\t.Username\x1a\x06.Users\"\x00\x30\x01\x12\x31\n\nDisconnect\x12\t.Username\x1a\x16.google.protobuf.Empty\"\x00\x12\x34\n\tStartGame\x12\x11.StartGameRequest\x1a\x12.StartGameResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mafia_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _USERNAME._serialized_start=44
  _USERNAME._serialized_end=68
  _USERS._serialized_start=70
  _USERS._serialized_end=106
  _STARTGAMEREQUEST._serialized_start=108
  _STARTGAMEREQUEST._serialized_end=178
  _STARTGAMERESPONSE._serialized_start=180
  _STARTGAMERESPONSE._serialized_end=249
  _MAFIA._serialized_start=252
  _MAFIA._serialized_end=398
# @@protoc_insertion_point(module_scope)
